version: '3.8'

services:
  db:
    container_name: postgres-rusoceans
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=rusocean1 ${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

  pgadmin:
    container_name: pgadminide
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ferubko1999@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: qwerty
    ports:
      - "5050:80"


