version: '3.8'

services:
  db:
    container_name: postgres-rusoceans2
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=rusocean2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadminide
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ferubko1999@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: qwerty
    ports:
      - "5050:80"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=red
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'